version: "3.8"

networks:
  app:
    driver: bridge

volumes:
  redis:
    driver: local

services:
  bot:
    restart: unless-stopped
    container_name: bot
    networks:
      - app
    env_file:
      - .env
    build:
      args:
        MODULE: bot
        MODE: ${MODE}
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
      - ~/bot_config:/bot_config

  redis:
    restart: unless-stopped
    container_name: redis
    networks:
      - app
    image: redis:6.2-alpine
    env_file:
      - .env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
